#!/usr/bin/perl -w
#Time-stamp: <Last updated: Zhao,Yafan zhaoyafan@mail.thu.edu.cn 2013-11-25 13:49:47>
#This script will calculate the Zero point energy from freq.dat file generated by dymmatrix.pl 
#This is just a clone of dymzpbar.pl. I just want to have a try.
#It works. :)
use strict;
use constant DEBUG=>0;
#Define a constant to convert cm^-1 to eV.
use constant CM2EV=>1.2398e-4;
my $data=$ARGV[0];
my $line;
my @freqlist;
my @freq;
my $tmp_freq;
my $i=0;
my $negfreq=0;
my $zpe=0;
open(DATA, "<",$data) || die "Failed to open file $data: $!\n";
while ($line=<DATA>){
    chomp $line;
    $line=~s/^\s+|\s+$//g;
    @freq=split(/\s+/,$line);
    $tmp_freq=$freq[0]*((-1)**$freq[3]);
    push (@freqlist,$tmp_freq);
    $i++;
    if (DEBUG){
	print "$i: $tmp_freq cm^{-1}\n";
    }
}


#ZPE=0.5*sum{vib energy}
for my $freq(@freqlist){
    if ($freq<0){
	$negfreq++;
   }else{
       $zpe+=0.5*$freq*CM2EV;
   }
}
print $negfreq," NEGATIVE EIGENVALUE FOUND ! \n" ;
print " ZERO-POINT ENERGY CONTRIBUTION FROM THE POSITIVE CURVATURE MODES = \n" ;
print $zpe," eV \n" ;
